version: 1.3.0.4
image: Visual Studio 2017

 
platform:
    - x86
    - x64

configuration:
    - Release

install:
    - if "%platform%"=="x64" set archi=amd64
    - if "%platform%"=="x64" set platform_input=x64

    - if "%platform%"=="x86" set archi=x86
    - if "%platform%"=="x86" set platform_input=x86

    - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %archi%

build_script:
    - cd "%APPVEYOR_BUILD_FOLDER%"\"Remove dup lines"
    - msbuild "Remove dup lines.sln" /m /p:configuration="%configuration%" /p:platform="%platform_input%" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

after_build:
    - cd "%APPVEYOR_BUILD_FOLDER%"\"Remove dup lines"\"Remove dup lines"
    - ps: >-

        Push-AppveyorArtifact "bin\$($env:PLATFORM_INPUT)\$($env:CONFIGURATION)\Remove_Duplicate_Lines.dll" -FileName Remove_Duplicate_Lines.dll

        if ($($env:APPVEYOR_REPO_TAG) -eq "true" -and $env:CONFIGURATION -eq "Release") {
            if($env:PLATFORM_INPUT -eq "x64"){
                $ZipFileName = "Remove_dup_lines_$($env:APPVEYOR_REPO_TAG_NAME)_x64.zip"
                7z a $ZipFileName bin\$env:PLATFORM_INPUT\$env:CONFIGURATION\Remove_Duplicate_Lines.dll
            }
            if($env:PLATFORM_INPUT -eq "x86"){
                $ZipFileName = "Remove_dup_lines_$($env:APPVEYOR_REPO_TAG_NAME)_x86.zip"
                7z a $ZipFileName bin\$env:PLATFORM_INPUT\$env:CONFIGURATION\Remove_Duplicate_Lines.dll
            }
        }

artifacts:
  - path: Remove_dup_lines_*.zip
    name: releases

deploy:
    provider: GitHub
    auth_token:
        secure: !!TODO !!
    artifact: releases
    draft: false
    prerelease: false
    force_update: true
    on:
        appveyor_repo_tag: true
        configuration: Release
